#!/bin/sh

set -e

if [ -z "$KEYFILE" ]; then
    KEYFILE="$(dirname $0)/my-tsig.key"
fi
NSUPDATE="nsupdate -k $KEYFILE"
NSSERVER=${NSSERVER:-localhost}
DOMAINSUFFIX=${DOMAINSUFFIX:-""}
TTL=${TTL:-60}

if [ $# -lt 2 ]; then
    echo "Usage: $0 setup|teardown <domain> [args...]" >&2
    exit 1
fi

case "$1" in
    setup)
        DOMAIN="$2$DOMAINSUFFIX"
        KEYAUTH="$3"
        printf "server %s\nupdate delete _acme-challenge.%s. TXT\nupdate add _acme-challenge.%s. %d TXT \"%s\"\nsend\n" $NSSERVER $DOMAIN $DOMAIN $TTL $KEYAUTH | $NSUPDATE
        ;;
    teardown)
        DOMAIN="$2$DOMAINSUFFIX"
        printf "server %s\nupdate delete _acme-challenge.%s. TXT\nsend\n" $NSSERVER $DOMAIN | $NSUPDATE
        ;;
    *)
        echo "Unknown action: $1" >&2
        exit 1
        ;;
esac
